apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: book-details-k8s
  ports:
    - port: 8080
      targetPort: 8081
  externalTrafficPolicy: Local
  type: LoadBalancer
